### ISSUE TITLE
cannot access URL links within Outlook emails

### ISSUE THREAD

**Issue by bharagan** [MicrosoftDocs/OfficeDocs-o365seccomp#321] opened 2019-01-29 17:12 UTC
Suddenly, this morning, I cannot access URL links to VERY SAFE sites (such as the Washington Post) from my laptop and iPhone Outlook email accounts. I get either HTTTP error 303 or 503 messages OR Office 365 messages telling me that the URL IS DANGEROUS! How can I re-set the Office 365 settings?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5939440-a0f8-0938-e61e-27aeca97888a
* Version Independent ID: 0314d705-b3fd-8533-22bd-a14039362e0f
* Content: [Office 365 Advanced Threat Protection](https://docs.microsoft.com/en-us/office365/securitycompliance/office-365-atp?redirectSourcePath=%252fen-us%252farticle%252fOffice-365-Advanced-Threat-Protection-e100fe7c-f2a1-4b7d-9e08-622330b83653#feedback)
* Content Source: [SecurityCompliance/office-365-atp.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/office-365-atp.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by cpliddle** [comment] 2019-01-29 17:41
Hello!  The same thing is happening to me today.  I get a few responses when clicking a link to a document or site from an Outlook email:

The page that you are trying to access cannot be loaded.
Due to an internal error, this web page could not be loaded. We recommend that you close this page.
Office 365 Advanced Threat Protection has encountered an error.

I received the above response to this link:
https://apc01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fclick.email.tasteofhome.com%2F%3Fqs%3Dfc0e981a6aab8bd93eda6f7cd3f045ea04b2258251a9db13752bc5fa2401ea857f9a52bee7fa2226d8bfb5925c164b62dcde68aba0090738&data=02%7C01%7C%7Ce1b6fccdef3f4e2b90ca08d68610334f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636843801467457359&sdata=rwZ1Rw2LL8Lco7zxD9aBGAH9nymccwwUmHTFkYDQdOc%3D&reserved=0

**Comment by bharagan** [comment] 2019-01-29 17:44
You received a link to a pressure cooker recipe as a response???

**Comment by hrhqc** [comment] 2019-01-29 17:45
I am also having this problem and in trying to sign up to GitHub when I clicked on the email to verify my email address that was blocked as well!

**Comment by huajatollas** [comment] 2019-01-29 18:24
I'm having the same problem. Every site with a link in my hotmail emails takes me to some dead page. I tried clearing cookies at that doesnt help. It says my Office 365 has been updated...well...the update has been a mess then. This is really annoying and I cant figure out how to turn off this safelinks thing so I can do what I need. Any advice?

**Comment by cpliddle** [comment] 2019-01-29 18:36
> You received a link to a pressure cooker recipe as a response???

Um....no.  As stated, that was the link that I received the error on.

**Comment by bharagan** [comment] 2019-01-29 18:40
Thank goodness!

**Comment by huajatollas** [comment] 2019-01-29 18:46
Does anyone monitor this thread to see if there are problems?

**Comment by lemonade2** [comment] 2019-01-29 19:08
I have been having this same problem for days! I have jumped through all kinds of hoops, thinking it was my internet, my computer, my browser. I have run virus and malware scans cleared history, cookies, reinstalled my browser, and cursed, a lot! I hope someone does monitor this and answers so this can be resolved. If they do though, will they send emails or responses of some type?

**Comment by mmhorning** [comment] 2019-01-29 19:10
Same problem for me.

**Comment by 22Tulio** [comment] 2019-01-29 19:12
Happening to me also.  Cannot open anything from mail.

**Comment by relax42day** [comment] 2019-01-29 19:53
Same here. All links fail, including the verification for Github! 
It's driving me nuts! 
Anyone know how to fix it????

**Comment by lemonade2** [comment] 2019-01-29 20:13
I have another question since I am just a senior trying to stay entertained with my computer, what is this github, and where did it come from. I never knew anything about it until I started digging to find out what i the world was going on with this.

**Comment by relax42day** [comment] 2019-01-29 20:31
Good summary here: https://en.wikipedia.org/wiki/GitHub

**Comment by andyhinz2** [comment] 2019-01-29 20:39
I see no response from Microsoft, have the same problem.  Um, are you trying to shed Office 365 customers Satya?

**Comment by huajatollas** [comment] 2019-01-29 20:43
I cant even get back to the Github conversation now cause the link wont work....

--
Jim O'Donnell, MCRP, CPD
Freelance Writer/Photographer
PO Box 3651, Taos, NM 87571 USA
www.aroundtheworldineightyyears.com<http://www.aroundtheworldineightyyears.com/>
http://www.jimodonnellphotography.com/


________________________________

**Comment by relax42day** [comment] 2019-01-29 20:44
Cut and paste the link into Chrome. That seems to bypass the issue.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by andyhinz2** [comment] 2019-01-29 20:45
I just tweeted this out @satyanadella whats going on with #Office365 #AdvancedThreatProtection #Outlook unusable today with most trusted links #FalsePositive  time for me to switch to #GoogleDocs I spose

**Comment by huajatollas** [comment] 2019-01-29 20:45
I cant find the URL

--
Jim O'Donnell, MCRP, CPD
Freelance Writer/Photographer
PO Box 3651, Taos, NM 87571 USA
www.aroundtheworldineightyyears.com<http://www.aroundtheworldineightyyears.com/>
http://www.jimodonnellphotography.com/


________________________________

**Comment by gked** [comment] 2019-01-29 22:08
+1

**Comment by huajatollas** [comment] 2019-01-29 22:34
It looks to me like the issue is fixed now. Others?

**Comment by bharagan** [comment] 2019-01-30 15:13
Resolved for me -- hooray!!

**Comment by relax42day** [comment] 2019-01-30 16:27
Me too

**Comment by hrhqc** [comment] 2019-01-30 16:54
and me, it went as suddenly as it appeared

**Comment by denisebmsft** [comment] 2019-01-30 17:45
Thank you all so much for posting about this. I apologize for the inconvenience. We are looking into this.

**Comment by bharagan** [comment] 2019-01-30 17:50
The problem disappeared for me!
________________________________

**Comment by denisebmsft** [comment] 2019-01-30 17:58
@bharagan thanks for the update!

**Closed by denisebmsft** 2019-01-30 17:58 UTC
Labels: bug
