### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by vishalgd** [MicrosoftDocs/OfficeDocs-o365seccomp#141] opened 2018-10-24 08:58 UTC
[Enter feedback here]

You should always give full details. Followed the link in O365 anti spam rule section but unable to find the option there. So logging the call now with O365 support team.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b6abf8b-ab18-1185-f53d-9c6aef9e3c3c
* Version Independent ID: cf94f179-0ce3-fe16-f903-a68cdbb7cf65
* Content: [Use user spam notifications to release and report quarantined messages in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/use-spam-notifications-to-release-and-report-quarantined-messages)
* Content Source: [SecurityCompliance/use-spam-notifications-to-release-and-report-quarantined-messages.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-spam-notifications-to-release-and-report-quarantined-messages.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment] 2018-10-24 19:32
@vishalgd Thank you for this feedback

We apricate you pointing out where we can improve the docs. I will make sure this gets to the o365seccomp for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by vishalgd** [comment] 2018-10-25 05:16
Thanks for acknoeledgement.

Thanks & Regards,
Vishal Govind Dewane

**Comment by vishalgd** [comment] 2018-10-25 12:04
Hope this ticket number will closed when document is updated & not when it is assigned.

**Comment by MSFTTracyP** [comment] 2019-01-28 21:48
@vishalgd -  What link are you referring to? What 'O365 anti spam rule section'? The only link I see is in the TIP. That link goes to 'Configure your spam filter policies' here: https://docs.microsoft.com/en-us/office365/SecurityCompliance/configure-your-spam-filter-policies. We need to know the broken link to update it, otherwise, we will have to close this (there are a lot of customer questions around here to answer)! Please get back to me and let me know. Also, I'm hoping that your call to Support went well and you're up and safely running!

**Comment by vishalgd** [comment] 2019-01-29 06:42
@MSFTTracyP  -  This issue is already closed in ticket #144 on 07-Dec-2018.

Also after contacting support they were not able to provide exact documentation on detailed phishing policy in which by design it is mentioned that when a mail is marked as phishing notification will not be send to user. Will send you details in mail as well.

**Comment by vishalgd** [comment] 2019-01-29 06:46
Hi MSFTTracyP,

PFA last mail thread for spam filter and phishing notifications in which they cannot find the exact documentation which says that if a mail is marked as phishing by design mail will not be send.

Thanks & Regards,
Vishal Govind Dewane
Dusane Infotech India Private Limited
Email ID - vishald@dusaneinfotech.com<mailto:vishald@dusaneinfotech.com> | http://www.dusaneinfotech.com<http://www.dusaneinfotech.com/>

**Comment by MSFTTracyP** [comment] 2019-01-30 18:55
@vishal-gandhi - Are you currently saying that you can't find Spam or Phishing documentation where it says an email marked as a Phishing attempt won't (by design) be sent _to the end-user_? And Support couldn't find this documentation?

Here are a few I found.

- How to create an Anti-Phishing policy so that Administrators control where marked mails go: 
https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-anti-phishing-policies

- DMARC policy options Administrators can set (None, Reject, and Quarantine):
https://docs.microsoft.com/en-us/office365/SecurityCompliance/use-dmarc-to-validate-email

- Quarantine options for Administrators in Office 365 for filtered mails
 https://docs.microsoft.com/en-us/office365/securitycompliance/manage-quarantined-messages-and-files

Please feel free to read our documentation for more.

Thanks,
Tracy

**Closed by MSFTTracyP** 2019-01-30 18:55 UTC

**Comment by EHLOBen** [comment] 2019-03-12 08:12
@MSFTTracyP Following those links you've provided above, I cannot find anything which specifically states messages marked as PHISH will not be visible to the end user via the Quarantine digest. - the issue here is not that they are not sent to the user, but that when they are quarantined, there is no notification sent.
