### ISSUE TITLE
Mail Flow Quarantine Notifications

### ISSUE THREAD

**Issue by msywulak** [MicrosoftDocs/OfficeDocs-o365seccomp#691] opened 2019-05-29 18:23 UTC
"Messages that are quarantined because they matched a mail flow rule are not included in user quarantined messages. Only spam-quarantined messages are listed."

This doesn't really make sense functionality wise at all. Why can users see messages that Microsoft chooses to quarantine but not from admins using transport rules? Admins have the ability to quarantine for a reason why not have notifications just work for everything in it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b6abf8b-ab18-1185-f53d-9c6aef9e3c3c
* Version Independent ID: cf94f179-0ce3-fe16-f903-a68cdbb7cf65
* Content: [Use user spam notifications to release and report quarantined messages in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/use-spam-notifications-to-release-and-report-quarantined-messages#feedback)
* Content Source: [SecurityCompliance/use-spam-notifications-to-release-and-report-quarantined-messages.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-spam-notifications-to-release-and-report-quarantined-messages.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment] 2019-06-03 23:54
@msywulak Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by get-itips** [comment] 2019-07-09 12:04
Duplicate of https://github.com/MicrosoftDocs/OfficeDocs-o365seccomp/issues/688

**Comment by get-itips** [comment] 2019-07-16 15:55
@scanum please close this one. Thanks

**Comment by scanum** [comment] 2019-08-19 06:33
@msywulak Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment] 2019-08-19 06:34
@officedocsbot close

**Closed by scanum** 2019-08-19 06:34 UTC
