### ISSUE TITLE
Invite guest AAD user to work with us in Compliance Manager

### ISSUE THREAD

**Issue by alexjeitler** [MicrosoftDocs/OfficeDocs-o365seccomp#484] opened 2019-03-14 08:55 UTC
It's not clear for me if it's supposed to work to invite an guest AAD user (eg. an external consultant) to work in our Compliance Manager tenant. Because it seems not to work, but I'm not sure if we're doing anything wrong or that feature is not implemented yet.

**Comment by denisebmsft** [comment] 2019-03-14 18:25
Hello @alexjeitler. Does your question pertain to this article: https://docs.microsoft.com/en-us/office365/securitycompliance/meet-data-protection-and-regulatory-reqs-using-microsoft-cloud

This will help me route the issue to the correct writer.

Thanks!

**Comment by alexjeitler** [comment] 2019-03-14 19:30
Exactly. Thank you.
Kind regards.

Sent from my mobile device.

________________________________

**Comment by markjjo** [comment] 2019-03-15 21:35
@alexjeitler What specific steps have you taken to give the external consultant access to Compliance Manager? What happens when the external consultant tries to sign in to Compliance Manager in your organization?

**Comment by alexjeitler** [comment] 2019-03-18 07:25
Hello Mark,


  *   Added external User to our Azure AD ourcompany.onmicrosoft.com
  *   Added external User on https://servicetrust.microsoft.com/Settings to Compliance-Manager-Reader Role

If he logs in with his user@externcompanydomain.com Account to https://servicetrust.microsoft.com he cannot see anything from ourcompnay.onmicrosoft.com Compliance Manager.

Thx and KR
Alex Jeitler.

**Comment by markjjo** [comment] 2019-03-19 19:04
@alexjeitler Thanks for the steps. I assume that you added the external user as a guest user in AAD. The issue is that when the external user tries to log in to Compliance Manager, he is using the credentials from his organization, not yours. So he actually logs into Compliance Manger for his org, not yours. The other problem that I was able to repo is the he probably can't log in to Compliance Manager using the username that is assigned to the guest account; for example, something like; johndoe_externaldomain.com#EXT#@contoso.onmicrosoft.com. When I try to use this username I can't log in because any password I use isn't accepted. The only workaround I have discovered is that you would have to create a normal user account (not a guest account) for the external user in your AAD and not assigned this account any kind of license. Then when you add this user account to a role in Compliance Manager, the external user will be able to sign in to Compliance Manager using the AAD credentials. You'll have to identify any risks/consequences by creating an AAD user account for the external user. Otherwise, I would suggest you open a support ticket with [Microsoft Support](https://support.microsoft.com) and how an guest user (using guest user credentials) sign into compliance manager for your org. Alternatively, you could provide feedback at https://office365.uservoice.com/

Finally, here is some more info about guest users in AAD: https://docs.microsoft.com/en-us/azure/active-directory/b2b/user-properties.

I will also update the compliance manager topic and remove reference about the "guest role" which is confusing; the gist is that any user will have a limited experience if they are not assigned to a Compliance Manager role.

**Closed by markjjo** 2019-03-19 19:04 UTC
Labels: question
